### ISSUE TITLE
Support 25C (T2123)

### ISSUE THREAD

**Issue by bikotoru** [mitchellrj/eufy_robovac#19]
when I try to configure my eufy 25C it does not connect, it crashes due to timeout, and I get the following error log

```

ogger: homeassistant.components.vacuum
Source: custom_components/eufy_vacuum/tuya.py:484
Integration: Aspiradora (documentation, issues)
First occurred: 21:10:47 (1 occurrences)
Last logged: 21:10:47

eufy_vacuum: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/eufy_vacuum/tuya.py", line 482, in async_connect
    sock.connect((self.host, self.port))
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 75, in async_update
    await self.robovac.async_get()
  File "/config/custom_components/eufy_vacuum/tuya.py", line 506, in async_get
    return await message.async_send(self, callback)
  File "/config/custom_components/eufy_vacuum/tuya.py", line 352, in async_send
    await device._async_send(self)
  File "/config/custom_components/eufy_vacuum/tuya.py", line 571, in _async_send
    await self.async_connect()
  File "/config/custom_components/eufy_vacuum/tuya.py", line 484, in async_connect
    raise ConnectionTimeoutException("Connection timed out") from e
custom_components.eufy_vacuum.tuya.ConnectionTimeoutException: Connection timed out
```

setting:
```
eufy_vacuum:
  devices:
  - name: Robovac
    address: 192.168.1.143
    access_token: 89dbee509ca02194
    id: 46014580bcddc2363989
    type: T2118

```

**Comment by jtomasrl** [comment]
are you sure you're not having other type of problems (network maybe)? Im using mine without any issues

**Comment by bikotoru** [comment]
> are you sure you're not having other type of problems (network maybe)? Im using mine without any issues

by the app it works without any problem.
can you share your yaml with me?

**Comment by jtomasrl** [comment]
> > are you sure you're not having other type of problems (network maybe)? Im using mine without any issues
> 
> by the app it works without any problem.
> can you share your yaml with me?

I have the same as you

```
eufy_vacuum:
  devices:
  - name: Robovac
    address: 192.168.5.1x  # my IoT network
    access_token: 41...a3  # 16 char
    id: 55...db2  # 20 char
    type: T2118
```

**Comment by MonsterEnergy-wtf** [comment]
I highly suggest not to use IP. 
Use the combination of deviceId" and "localKey" as they are discovered automatically. 

I remember that there was any trouble related to IP... But I don't remember it correctly.
 
@jtomasrl can you please give it a shot?
