### ISSUE TITLE
Support for T2130

### ISSUE THREAD

**Issue by Anon0ne** [mitchellrj/eufy_robovac#22]
Any chance this will be supported?

```
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 50, in setup_platform
    add_entities([EufyVacuum(device_config)], True)
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 62, in __init__
    raise RuntimeError("Unsupported model {}".format(
RuntimeError: Unsupported model T2130
```

**Comment by xSp0Tx** [comment]
Hello there,

Same here with T2150



Traceback (most recent call last):
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 60, in __init__
    self._config = MODEL_CONFIG[device_config['model'].upper()]
**KeyError: 'T2150'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 50, in setup_platform
    add_entities([EufyVacuum(device_config)], True)
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 62, in __init__
    raise RuntimeError("Unsupported model {}".format(
**RuntimeError: Unsupported model T2150**

Is there anyway to Support this one too? I´ve tried several other Implementations but none worked.

i just tried another type (2118) and it showed me my vacuum entity. i could add an entity card that shows an error instead of any values but i can control the Robovac. maybe this helps 🤷

**Comment by Sloshmold** [comment]
> Hello there,
> 
> Same here with T2150
> 
> Traceback (most recent call last): File "/config/custom_components/eufy_vacuum/vacuum.py", line 60, in **init** self._config = MODEL_CONFIG[device_config['model'].upper()] **KeyError: 'T2150'**
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform await asyncio.shield(task) File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/eufy_vacuum/vacuum.py", line 50, in setup_platform add_entities([EufyVacuum(device_config)], True) File "/config/custom_components/eufy_vacuum/vacuum.py", line 62, in **init** raise RuntimeError("Unsupported model {}".format( **RuntimeError: Unsupported model T2150**
> 
> Is there anyway to Support this one too? I´ve tried several other Implementations but none worked.
> 
> i just tried another type (2118) and it showed me my vacuum entity. i could add an entity card that shows an error instead of any values but i can control the Robovac. maybe this helps 🤷

Did you find a fix for this yet?
