### ISSUE TITLE
Support for T2250 (Robovac G30)

### ISSUE THREAD

**Issue by gorobotgo** [mitchellrj/eufy_robovac#23]
Vacuum type T2250 (Eufy Robovac G30) is currently reported as not supported, and does not work when forced as a T2118 (results in a decryption error when connecting).

**Comment by xSp0Tx** [comment]
Hello there,

Same here with T2150 (G10)

Traceback (most recent call last):
File "/config/custom_components/eufy_vacuum/vacuum.py", line 60, in init
self._config = MODEL_CONFIG[device_config['model'].upper()]
KeyError: 'T2150'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/eufy_vacuum/vacuum.py", line 50, in setup_platform
add_entities([EufyVacuum(device_config)], True)
File "/config/custom_components/eufy_vacuum/vacuum.py", line 62, in init
raise RuntimeError("Unsupported model {}".format(
RuntimeError: Unsupported model T2150

Is there anyway to Support this one too? I´ve tried several other Implementations but none worked.

i just tried another type (2118) and it showed me my vacuum entity. i could add an entity card that shows an error instead of any values but i can control the Robovac. maybe this helps 🤷

**Comment by colonelmattyman** [comment]
I have the G30 also (model 2252). I can also add 2118 and status and battery all error out as well. I can also start and stop it like xSp0Tx.
If you'd like to provide instructions on how we can extract the codes you'd need for the other models, I'd be happy to try and extract them.

**Comment by silviudc** [comment]
Hi guys, I am having the same issues, set it up as a T2118 model and logs an error whenever performing actions and no status or battery.
I really need to get this working, any luck?

**Comment by silviudc** [comment]
The messages are quite different between the T2118 and the T2250
T2118:
`Message(0xa, {'devId': '0753038684f3exxxxx', 'dps': {'1': True, '2': False, '3': 'back', '5': 'Nosweep', '15': 'completed', '101': False, '102': 'No_suction', '103': False, '104': 100, '106': 'no_error'}}, 891149639, None)`
T2250
`Message(0xa, {'dps': {'1': True, '2': False, '5': 'Nosweep', '15': 'standby', '102': 'Boost_IQ', '103': False, '104': 81, '106': 0, '107': False, '109': 1020, '110': 13, '111': 4, '122': 'Nosweep', '128': 'default', '130': 'No_suction', '131': False, '132': 1033, '133': 13, '134': 1, '135': False, '137': 0, '140': '0004100013010331096'}}, 891149643, None)`
